//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieLanguage
    {
        public long MovieId { get; set; }
        public int LanguageId { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
