//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosterInfo
    {
        public long Id { get; set; }
        public string Imdb { get; set; }
        public string Cover { get; set; }
        public long MovieId { get; set; }
        public string LocalPath { get; set; }
        public byte[] Image { get; set; }
        public string LocalFolderPath { get; set; }
        public string ImdbID { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
